server:
  port: 21003
  servlet:
    context-path: /api
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    serialization:
      write-dates-as-timestamps: false
  logging:
    level:
      org.springframework.web: DEBUG
  cloud:
    appId: kubernetes-practice-230221
