server:
  port: 21002
  servlet:
    context-path: /api/inventory
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    serialization:
      write-dates-as-timestamps: false
  logging:
    level:
      org.springframework.web: DEBUG