package cxf.wsdl.wgmartinez.co.invoice_ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-10T15:37:38.266+11:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://co.wgmartinez.wsdl/invoice-ws/", name = "InvoiceServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InvoiceServicePortType {

    @WebMethod(action = "http://co.wgmartinez.wsdl/invoice-ws/addInvoice")
    @WebResult(name = "addInvoiceResponse", targetNamespace = "http://co.wgmartinez.wsdl/invoice-ws/", partName = "addInvoiceResponse")
    public AddInvoiceResponse addInvoice(
            @WebParam(partName = "addInvoiceRequest", name = "addInvoiceRequest", targetNamespace = "http://co.wgmartinez.wsdl/invoice-ws/")
                    AddInvoiceRequest addInvoiceRequest
    );
}
